"""Added cascade delete

Revision ID: 0e99a74bb4b2
Revises: da114949824c
Create Date: 2024-10-21 17:33:58.026210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e99a74bb4b2'
down_revision: Union[str, None] = 'da114949824c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('AllBets_acc_id_fkey', 'AllBets', type_='foreignkey')
    op.create_foreign_key(None, 'AllBets', 'Accounts', ['acc_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Bets_acc_id_fkey', 'Bets', type_='foreignkey')
    op.create_foreign_key(None, 'Bets', 'Accounts', ['acc_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Bets', type_='foreignkey')
    op.create_foreign_key('Bets_acc_id_fkey', 'Bets', 'Accounts', ['acc_id'], ['id'])
    op.drop_constraint(None, 'AllBets', type_='foreignkey')
    op.create_foreign_key('AllBets_acc_id_fkey', 'AllBets', 'Accounts', ['acc_id'], ['id'])
    # ### end Alembic commands ###
