"""Bet type and Bet on

Revision ID: 3d4cdae99331
Revises: 4a430017270f
Create Date: 2024-02-28 15:53:09.664099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4cdae99331'
down_revision: Union[str, None] = '4a430017270f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bets', sa.Column('bet_on', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bets', 'bet_on')
    # ### end Alembic commands ###
