"""added parsed bet model

Revision ID: 5e52f215ddb0
Revises: fd49732a17e1
Create Date: 2024-10-30 19:39:01.268055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e52f215ddb0'
down_revision: Union[str, None] = 'fd49732a17e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ParsedBets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_return', sa.Float(), nullable=True),
    sa.Column('acc_id', sa.Integer(), nullable=True),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acc_id'], ['Accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bet_id'], ['Bets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ParsedBets')
    # ### end Alembic commands ###
