"""База данных новая версия

Revision ID: 7615afcfbec4
Revises: b6458f8c63e3
Create Date: 2024-02-22 11:48:40.768117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7615afcfbec4'
down_revision: Union[str, None] = 'b6458f8c63e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Accounts', 'balance')
    op.add_column('Bets', sa.Column('balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bets', 'balance')
    op.add_column('Accounts', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
