"""Added sport and league to Bets

Revision ID: 79161a648c59
Revises: aa8c47193de8
Create Date: 2024-10-31 16:05:21.947660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79161a648c59'
down_revision: Union[str, None] = 'aa8c47193de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bets', sa.Column('sport', sa.String(), nullable=True))
    op.add_column('Bets', sa.Column('league', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bets', 'league')
    op.drop_column('Bets', 'sport')
    # ### end Alembic commands ###
