"""Added stake to parsed bets

Revision ID: aa8c47193de8
Revises: b0762dbbe8a7
Create Date: 2024-10-31 13:05:25.694225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8c47193de8'
down_revision: Union[str, None] = 'b0762dbbe8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ParsedBets', sa.Column('stake', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ParsedBets', 'stake')
    # ### end Alembic commands ###
