"""Models v 1.0

Revision ID: b6458f8c63e3
Revises: d9ec39b1f7fa
Create Date: 2024-02-21 15:29:17.296409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6458f8c63e3'
down_revision: Union[str, None] = 'd9ec39b1f7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Bets', sa.Column('acc_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Bets', 'Accounts', ['acc_id'], ['id'])
    op.drop_column('Bets', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bets', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Bets', type_='foreignkey')
    op.drop_column('Bets', 'acc_id')
    op.drop_table('Accounts')
    # ### end Alembic commands ###
