"""Arb table added

Revision ID: b97d91f209d7
Revises: 3d4cdae99331
Create Date: 2024-03-26 17:13:38.715003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97d91f209d7'
down_revision: Union[str, None] = '3d4cdae99331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Arbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bk1_koef', sa.Float(), nullable=True),
    sa.Column('bk1_pre_koef', sa.Float(), nullable=True),
    sa.Column('bk2_koef', sa.Float(), nullable=True),
    sa.Column('arb', sa.Float(), nullable=True),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bet_id'], ['Bets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Arbs')
    # ### end Alembic commands ###
