"""Value added

Revision ID: da114949824c
Revises: fd4f16583fcf
Create Date: 2024-10-14 13:40:22.162016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da114949824c'
down_revision: Union[str, None] = 'fd4f16583fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Bets', 'bet_type', new_column_name='market')
    op.alter_column('Bets', 'arb', new_column_name='arb_or_value_percent')
    op.add_column('Bets', sa.Column('arb_or_value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Bets', 'market', new_column_name='bet_type')
    op.alter_column('Bets', 'arb_or_value_percent', new_column_name='arb')
    op.drop_column('Bets', 'arb_or_value')
    # ### end Alembic commands ###
